#!/bin/sh

#CLASSPATH=/usr/share/java/log4j-1.2.jar:/usr/share/java/slf4j-api.jar:/usr/share/java/slf4j-simple.jar:/usr/share/java/zookeeper.jar:/usr/share/zookeeper/zooinspector/zookeeper-zooinspector.jar
#Source classpath from zookeeper configs
#source /etc/zookeeper/conf/environment
#No need to classpath as we are using jar with dependencies
# We have to cd to this dir so that the icons are found
#cd /usr/share/zookeeper/zooinspector

java -cp $CLASSPATH org.apache.zookeeper.inspector.ZooInspector
